### ISSUE TITLE
Remove the feature of multi-language support said by @Akshat Jain bhaiya

### ISSUE THREAD

**Issue by amartya-mondal** [NJACKWinterOfCode/WhatsApp-Direct-Message#80]

**Comment by amartya-mondal** [comment]
I am working on it.

**Comment by roshniRam** [comment]
Hey Amartya, a suggestion, actually the aim of the issue which I had created was that if on someone's phone the default language is set to suppose Hindi, then all the content should be displayed in Hindi. There was no need for a select language spinner in the layout. So what you can is, remove the select language spinner from the layout, and then make it compatible for other languages. Currently, I checked by changing my phone's default lang to Hindi and after opening the app the content is displayed in Hindi, but when I checked for Bengali it didn't work. So you work on this, instead of removing the code for multi lang support completely, just remove spinner from layout, and make it compatible to the phone default language.

**Comment by roshniRam** [comment]
Also, remove about us page and the background images of the theme.
